// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type AuthState struct {
	State        string    `json:"state"`
	Nonce        string    `json:"nonce"`
	RedirectUri  string    `json:"redirect_uri"`
	ProviderName string    `json:"provider_name"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type Session struct {
	ID         string       `json:"id"`
	UserID     string       `json:"user_id"`
	Issuer     string       `json:"issuer"`
	Subject    string       `json:"subject"`
	CreatedAt  time.Time    `json:"created_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	LastUsedAt time.Time    `json:"last_used_at"`
}

type User struct {
	ID              string         `json:"id"`
	HeadscaleUser   string         `json:"headscale_user"`
	Issuer          string         `json:"issuer"`
	Subject         string         `json:"subject"`
	Email           sql.NullString `json:"email"`
	Name            sql.NullString `json:"name"`
	Picture         sql.NullString `json:"picture"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	HeadscaleUserID int64          `json:"headscale_user_id"`
}
