// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, headscale_user, headscale_user_id, issuer, subject, email, name, picture, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID              string         `json:"id"`
	HeadscaleUser   string         `json:"headscale_user"`
	HeadscaleUserID int64          `json:"headscale_user_id"`
	Issuer          string         `json:"issuer"`
	Subject         string         `json:"subject"`
	Email           sql.NullString `json:"email"`
	Name            sql.NullString `json:"name"`
	Picture         sql.NullString `json:"picture"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.HeadscaleUser,
		arg.HeadscaleUserID,
		arg.Issuer,
		arg.Subject,
		arg.Email,
		arg.Name,
		arg.Picture,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, headscale_user, issuer, subject, email, name, picture, created_at, updated_at, headscale_user_id FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HeadscaleUser,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadscaleUserID,
	)
	return i, err
}

const getUserByHeadscaleUser = `-- name: GetUserByHeadscaleUser :one
SELECT id, headscale_user, issuer, subject, email, name, picture, created_at, updated_at, headscale_user_id FROM users WHERE headscale_user = ?
`

func (q *Queries) GetUserByHeadscaleUser(ctx context.Context, headscaleUser string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByHeadscaleUser, headscaleUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HeadscaleUser,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadscaleUserID,
	)
	return i, err
}

const getUserByIssuerSubject = `-- name: GetUserByIssuerSubject :one
SELECT id, headscale_user, issuer, subject, email, name, picture, created_at, updated_at, headscale_user_id FROM users WHERE issuer = ? AND subject = ?
`

type GetUserByIssuerSubjectParams struct {
	Issuer  string `json:"issuer"`
	Subject string `json:"subject"`
}

func (q *Queries) GetUserByIssuerSubject(ctx context.Context, arg GetUserByIssuerSubjectParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByIssuerSubject, arg.Issuer, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HeadscaleUser,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeadscaleUserID,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, headscale_user, issuer, subject, email, name, picture, created_at, updated_at, headscale_user_id FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.HeadscaleUser,
			&i.Issuer,
			&i.Subject,
			&i.Email,
			&i.Name,
			&i.Picture,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HeadscaleUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email = ?, name = ?, picture = ?, updated_at = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Email     sql.NullString `json:"email"`
	Name      sql.NullString `json:"name"`
	Picture   sql.NullString `json:"picture"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Email,
		arg.Name,
		arg.Picture,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
