// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id, user_id, name, api_key, scopes, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAPIKeyParams struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	Name      string       `json:"name"`
	ApiKey    string       `json:"api_key"`
	Scopes    string       `json:"scopes"`
	CreatedAt time.Time    `json:"created_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.ApiKey,
		arg.Scopes,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = ?
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const deleteAPIKeyByUser = `-- name: DeleteAPIKeyByUser :execresult
DELETE FROM api_keys WHERE id = ? AND user_id = ?
`

type DeleteAPIKeyByUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAPIKeyByUser(ctx context.Context, arg DeleteAPIKeyByUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAPIKeyByUser, arg.ID, arg.UserID)
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, user_id, name, api_key, scopes, created_at, expires_at, last_used_at FROM api_keys WHERE id = ?
`

func (q *Queries) GetAPIKey(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ApiKey,
		&i.Scopes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPIKeyByKey = `-- name: GetAPIKeyByKey :one
SELECT id, user_id, name, api_key, scopes, created_at, expires_at, last_used_at FROM api_keys WHERE api_key = ?
`

func (q *Queries) GetAPIKeyByKey(ctx context.Context, apiKey string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByKey, apiKey)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ApiKey,
		&i.Scopes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, name, api_key, scopes, created_at, expires_at, last_used_at FROM api_keys WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ApiKey,
			&i.Scopes,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = ? WHERE id = ?
`

type UpdateAPIKeyLastUsedParams struct {
	LastUsedAt sql.NullTime `json:"last_used_at"`
	ID         string       `json:"id"`
}

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
