// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id, realm_id, name, api_key, created_at, expires_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP, ?)
`

type CreateAPIKeyParams struct {
	ID        string       `json:"id"`
	RealmID   string       `json:"realm_id"`
	Name      string       `json:"name"`
	ApiKey    string       `json:"api_key"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKey,
		arg.ID,
		arg.RealmID,
		arg.Name,
		arg.ApiKey,
		arg.ExpiresAt,
	)
	return err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = ?
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const deleteAPIKeyByRealm = `-- name: DeleteAPIKeyByRealm :execresult
DELETE FROM api_keys WHERE id = ? AND realm_id = ?
`

type DeleteAPIKeyByRealmParams struct {
	ID      string `json:"id"`
	RealmID string `json:"realm_id"`
}

func (q *Queries) DeleteAPIKeyByRealm(ctx context.Context, arg DeleteAPIKeyByRealmParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAPIKeyByRealm, arg.ID, arg.RealmID)
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, realm_id, name, api_key, created_at, expires_at, last_used_at FROM api_keys WHERE id = ?
`

func (q *Queries) GetAPIKey(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.RealmID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPIKeyByKey = `-- name: GetAPIKeyByKey :one
SELECT id, realm_id, name, api_key, created_at, expires_at, last_used_at FROM api_keys WHERE api_key = ?
`

func (q *Queries) GetAPIKeyByKey(ctx context.Context, apiKey string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByKey, apiKey)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.RealmID,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listAPIKeysByRealm = `-- name: ListAPIKeysByRealm :many
SELECT id, realm_id, name, api_key, created_at, expires_at, last_used_at FROM api_keys WHERE realm_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByRealm(ctx context.Context, realmID string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByRealm, realmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.RealmID,
			&i.Name,
			&i.ApiKey,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, id)
	return err
}
