// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_states.sql

package sqlc

import (
	"context"
	"time"
)

const createAuthState = `-- name: CreateAuthState :exec
INSERT INTO auth_states (state, provider, redirect_url, created_at, expires_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP, ?)
`

type CreateAuthStateParams struct {
	State       string    `json:"state"`
	Provider    string    `json:"provider"`
	RedirectUrl string    `json:"redirect_url"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateAuthState(ctx context.Context, arg CreateAuthStateParams) error {
	_, err := q.db.ExecContext(ctx, createAuthState,
		arg.State,
		arg.Provider,
		arg.RedirectUrl,
		arg.ExpiresAt,
	)
	return err
}

const deleteAuthState = `-- name: DeleteAuthState :exec
DELETE FROM auth_states WHERE state = ?
`

func (q *Queries) DeleteAuthState(ctx context.Context, state string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthState, state)
	return err
}

const deleteExpiredAuthStates = `-- name: DeleteExpiredAuthStates :exec
DELETE FROM auth_states WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredAuthStates(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAuthStates)
	return err
}

const getAuthState = `-- name: GetAuthState :one
SELECT state, provider, redirect_url, created_at, expires_at FROM auth_states WHERE state = ?
`

func (q *Queries) GetAuthState(ctx context.Context, state string) (AuthState, error) {
	row := q.db.QueryRowContext(ctx, getAuthState, state)
	var i AuthState
	err := row.Scan(
		&i.State,
		&i.Provider,
		&i.RedirectUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
