// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_states.sql

package sqlc

import (
	"context"
	"time"
)

const createAuthState = `-- name: CreateAuthState :exec
INSERT INTO auth_states (state, nonce, redirect_uri, provider_name, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAuthStateParams struct {
	State        string    `json:"state"`
	Nonce        string    `json:"nonce"`
	RedirectUri  string    `json:"redirect_uri"`
	ProviderName string    `json:"provider_name"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) CreateAuthState(ctx context.Context, arg CreateAuthStateParams) error {
	_, err := q.db.ExecContext(ctx, createAuthState,
		arg.State,
		arg.Nonce,
		arg.RedirectUri,
		arg.ProviderName,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteAuthState = `-- name: DeleteAuthState :exec
DELETE FROM auth_states WHERE state = ?
`

func (q *Queries) DeleteAuthState(ctx context.Context, state string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthState, state)
	return err
}

const deleteExpiredAuthStates = `-- name: DeleteExpiredAuthStates :exec
DELETE FROM auth_states WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredAuthStates(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAuthStates)
	return err
}

const getAuthState = `-- name: GetAuthState :one
SELECT state, nonce, redirect_uri, provider_name, created_at, expires_at FROM auth_states WHERE state = ?
`

func (q *Queries) GetAuthState(ctx context.Context, state string) (AuthState, error) {
	row := q.db.QueryRowContext(ctx, getAuthState, state)
	var i AuthState
	err := row.Scan(
		&i.State,
		&i.Nonce,
		&i.RedirectUri,
		&i.ProviderName,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
