// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_requests.sql

package sqlc

import (
	"context"
	"time"
)

const approveDeviceRequest = `-- name: ApproveDeviceRequest :exec
UPDATE device_requests
SET status = 'approved',
    wonder_net_id = ?,
    headscale_user = ?,
    authkey = ?,
    headscale_url = ?,
    coordinator_url = ?
WHERE user_code = ? AND status = 'pending' AND expires_at > CURRENT_TIMESTAMP
`

type ApproveDeviceRequestParams struct {
	WonderNetID    string `json:"wonder_net_id"`
	HeadscaleUser  string `json:"headscale_user"`
	Authkey        string `json:"authkey"`
	HeadscaleUrl   string `json:"headscale_url"`
	CoordinatorUrl string `json:"coordinator_url"`
	UserCode       string `json:"user_code"`
}

func (q *Queries) ApproveDeviceRequest(ctx context.Context, arg ApproveDeviceRequestParams) error {
	_, err := q.db.ExecContext(ctx, approveDeviceRequest,
		arg.WonderNetID,
		arg.HeadscaleUser,
		arg.Authkey,
		arg.HeadscaleUrl,
		arg.CoordinatorUrl,
		arg.UserCode,
	)
	return err
}

const createDeviceRequest = `-- name: CreateDeviceRequest :exec
INSERT INTO device_requests (device_code, user_code, status, created_at, expires_at)
VALUES (?, ?, 'pending', ?, ?)
`

type CreateDeviceRequestParams struct {
	DeviceCode string    `json:"device_code"`
	UserCode   string    `json:"user_code"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) CreateDeviceRequest(ctx context.Context, arg CreateDeviceRequestParams) error {
	_, err := q.db.ExecContext(ctx, createDeviceRequest,
		arg.DeviceCode,
		arg.UserCode,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteDeviceRequest = `-- name: DeleteDeviceRequest :exec
DELETE FROM device_requests WHERE device_code = ?
`

func (q *Queries) DeleteDeviceRequest(ctx context.Context, deviceCode string) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceRequest, deviceCode)
	return err
}

const deleteExpiredDeviceRequests = `-- name: DeleteExpiredDeviceRequests :exec
DELETE FROM device_requests WHERE expires_at < datetime('now', '-1 minute')
`

func (q *Queries) DeleteExpiredDeviceRequests(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredDeviceRequests)
	return err
}

const getDeviceRequestByDeviceCode = `-- name: GetDeviceRequestByDeviceCode :one
SELECT device_code, user_code, status, wonder_net_id, headscale_user, authkey, headscale_url, coordinator_url, created_at, expires_at FROM device_requests WHERE device_code = ?
`

func (q *Queries) GetDeviceRequestByDeviceCode(ctx context.Context, deviceCode string) (DeviceRequest, error) {
	row := q.db.QueryRowContext(ctx, getDeviceRequestByDeviceCode, deviceCode)
	var i DeviceRequest
	err := row.Scan(
		&i.DeviceCode,
		&i.UserCode,
		&i.Status,
		&i.WonderNetID,
		&i.HeadscaleUser,
		&i.Authkey,
		&i.HeadscaleUrl,
		&i.CoordinatorUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getDeviceRequestByUserCode = `-- name: GetDeviceRequestByUserCode :one
SELECT device_code, user_code, status, wonder_net_id, headscale_user, authkey, headscale_url, coordinator_url, created_at, expires_at FROM device_requests WHERE user_code = ?
`

func (q *Queries) GetDeviceRequestByUserCode(ctx context.Context, userCode string) (DeviceRequest, error) {
	row := q.db.QueryRowContext(ctx, getDeviceRequestByUserCode, userCode)
	var i DeviceRequest
	err := row.Scan(
		&i.DeviceCode,
		&i.UserCode,
		&i.Status,
		&i.WonderNetID,
		&i.HeadscaleUser,
		&i.Authkey,
		&i.HeadscaleUrl,
		&i.CoordinatorUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const userCodeExists = `-- name: UserCodeExists :one
SELECT EXISTS(SELECT 1 FROM device_requests WHERE user_code = ? AND expires_at > CURRENT_TIMESTAMP) as exists_flag
`

func (q *Queries) UserCodeExists(ctx context.Context, userCode string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userCodeExists, userCode)
	var exists_flag int64
	err := row.Scan(&exists_flag)
	return exists_flag, err
}
