// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type DeviceRequest struct {
	DeviceCode     string    `json:"device_code"`
	UserCode       string    `json:"user_code"`
	Status         string    `json:"status"`
	WonderNetID    string    `json:"wonder_net_id"`
	HeadscaleUser  string    `json:"headscale_user"`
	Authkey        string    `json:"authkey"`
	HeadscaleUrl   string    `json:"headscale_url"`
	CoordinatorUrl string    `json:"coordinator_url"`
	CreatedAt      time.Time `json:"created_at"`
	ExpiresAt      time.Time `json:"expires_at"`
}

type ServiceAccount struct {
	ID               string    `json:"id"`
	WonderNetID      string    `json:"wonder_net_id"`
	KeycloakClientID string    `json:"keycloak_client_id"`
	Name             string    `json:"name"`
	CreatedAt        time.Time `json:"created_at"`
}

type WonderNet struct {
	ID            string    `json:"id"`
	OwnerID       string    `json:"owner_id"`
	HeadscaleUser string    `json:"headscale_user"`
	DisplayName   string    `json:"display_name"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}
