// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc_identities.sql

package sqlc

import (
	"context"
)

const createOIDCIdentity = `-- name: CreateOIDCIdentity :exec
INSERT INTO oidc_identities (id, user_id, issuer, subject, email, name, picture, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type CreateOIDCIdentityParams struct {
	ID      string `json:"id"`
	UserID  string `json:"user_id"`
	Issuer  string `json:"issuer"`
	Subject string `json:"subject"`
	Email   string `json:"email"`
	Name    string `json:"name"`
	Picture string `json:"picture"`
}

func (q *Queries) CreateOIDCIdentity(ctx context.Context, arg CreateOIDCIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createOIDCIdentity,
		arg.ID,
		arg.UserID,
		arg.Issuer,
		arg.Subject,
		arg.Email,
		arg.Name,
		arg.Picture,
	)
	return err
}

const deleteOIDCIdentitiesByUser = `-- name: DeleteOIDCIdentitiesByUser :exec
DELETE FROM oidc_identities WHERE user_id = ?
`

func (q *Queries) DeleteOIDCIdentitiesByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteOIDCIdentitiesByUser, userID)
	return err
}

const deleteOIDCIdentity = `-- name: DeleteOIDCIdentity :exec
DELETE FROM oidc_identities WHERE id = ?
`

func (q *Queries) DeleteOIDCIdentity(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteOIDCIdentity, id)
	return err
}

const getOIDCIdentity = `-- name: GetOIDCIdentity :one
SELECT id, user_id, issuer, subject, email, name, picture, created_at, updated_at FROM oidc_identities WHERE id = ?
`

func (q *Queries) GetOIDCIdentity(ctx context.Context, id string) (OidcIdentity, error) {
	row := q.db.QueryRowContext(ctx, getOIDCIdentity, id)
	var i OidcIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOIDCIdentityByIssuerSubject = `-- name: GetOIDCIdentityByIssuerSubject :one
SELECT id, user_id, issuer, subject, email, name, picture, created_at, updated_at FROM oidc_identities WHERE issuer = ? AND subject = ?
`

type GetOIDCIdentityByIssuerSubjectParams struct {
	Issuer  string `json:"issuer"`
	Subject string `json:"subject"`
}

func (q *Queries) GetOIDCIdentityByIssuerSubject(ctx context.Context, arg GetOIDCIdentityByIssuerSubjectParams) (OidcIdentity, error) {
	row := q.db.QueryRowContext(ctx, getOIDCIdentityByIssuerSubject, arg.Issuer, arg.Subject)
	var i OidcIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOIDCIdentitiesByUser = `-- name: ListOIDCIdentitiesByUser :many
SELECT id, user_id, issuer, subject, email, name, picture, created_at, updated_at FROM oidc_identities WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListOIDCIdentitiesByUser(ctx context.Context, userID string) ([]OidcIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listOIDCIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcIdentity{}
	for rows.Next() {
		var i OidcIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Issuer,
			&i.Subject,
			&i.Email,
			&i.Name,
			&i.Picture,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOIDCIdentity = `-- name: UpdateOIDCIdentity :exec
UPDATE oidc_identities
SET email = ?, name = ?, picture = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateOIDCIdentityParams struct {
	Email   string `json:"email"`
	Name    string `json:"name"`
	Picture string `json:"picture"`
	ID      string `json:"id"`
}

func (q *Queries) UpdateOIDCIdentity(ctx context.Context, arg UpdateOIDCIdentityParams) error {
	_, err := q.db.ExecContext(ctx, updateOIDCIdentity,
		arg.Email,
		arg.Name,
		arg.Picture,
		arg.ID,
	)
	return err
}
