// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: realms.sql

package sqlc

import (
	"context"
)

const createRealm = `-- name: CreateRealm :exec
INSERT INTO realms (id, owner_id, headscale_user, display_name, created_at, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type CreateRealmParams struct {
	ID            string `json:"id"`
	OwnerID       string `json:"owner_id"`
	HeadscaleUser string `json:"headscale_user"`
	DisplayName   string `json:"display_name"`
}

func (q *Queries) CreateRealm(ctx context.Context, arg CreateRealmParams) error {
	_, err := q.db.ExecContext(ctx, createRealm,
		arg.ID,
		arg.OwnerID,
		arg.HeadscaleUser,
		arg.DisplayName,
	)
	return err
}

const deleteRealm = `-- name: DeleteRealm :exec
DELETE FROM realms WHERE id = ?
`

func (q *Queries) DeleteRealm(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRealm, id)
	return err
}

const getRealm = `-- name: GetRealm :one
SELECT id, owner_id, headscale_user, display_name, created_at, updated_at FROM realms WHERE id = ?
`

func (q *Queries) GetRealm(ctx context.Context, id string) (Realm, error) {
	row := q.db.QueryRowContext(ctx, getRealm, id)
	var i Realm
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.HeadscaleUser,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRealmByHeadscaleUser = `-- name: GetRealmByHeadscaleUser :one
SELECT id, owner_id, headscale_user, display_name, created_at, updated_at FROM realms WHERE headscale_user = ?
`

func (q *Queries) GetRealmByHeadscaleUser(ctx context.Context, headscaleUser string) (Realm, error) {
	row := q.db.QueryRowContext(ctx, getRealmByHeadscaleUser, headscaleUser)
	var i Realm
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.HeadscaleUser,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRealms = `-- name: ListRealms :many
SELECT id, owner_id, headscale_user, display_name, created_at, updated_at FROM realms ORDER BY created_at DESC
`

func (q *Queries) ListRealms(ctx context.Context) ([]Realm, error) {
	rows, err := q.db.QueryContext(ctx, listRealms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Realm{}
	for rows.Next() {
		var i Realm
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.HeadscaleUser,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRealmsByOwner = `-- name: ListRealmsByOwner :many
SELECT id, owner_id, headscale_user, display_name, created_at, updated_at FROM realms WHERE owner_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListRealmsByOwner(ctx context.Context, ownerID string) ([]Realm, error) {
	rows, err := q.db.QueryContext(ctx, listRealmsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Realm{}
	for rows.Next() {
		var i Realm
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.HeadscaleUser,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRealm = `-- name: UpdateRealm :exec
UPDATE realms
SET display_name = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateRealmParams struct {
	DisplayName string `json:"display_name"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateRealm(ctx context.Context, arg UpdateRealmParams) error {
	_, err := q.db.ExecContext(ctx, updateRealm, arg.DisplayName, arg.ID)
	return err
}
