// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_accounts.sql

package sqlc

import (
	"context"
)

const createServiceAccount = `-- name: CreateServiceAccount :exec
INSERT INTO service_accounts (id, wonder_net_id, keycloak_client_id, name, created_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
`

type CreateServiceAccountParams struct {
	ID               string `json:"id"`
	WonderNetID      string `json:"wonder_net_id"`
	KeycloakClientID string `json:"keycloak_client_id"`
	Name             string `json:"name"`
}

func (q *Queries) CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) error {
	_, err := q.db.ExecContext(ctx, createServiceAccount,
		arg.ID,
		arg.WonderNetID,
		arg.KeycloakClientID,
		arg.Name,
	)
	return err
}

const deleteServiceAccount = `-- name: DeleteServiceAccount :exec
DELETE FROM service_accounts WHERE keycloak_client_id = ?
`

func (q *Queries) DeleteServiceAccount(ctx context.Context, keycloakClientID string) error {
	_, err := q.db.ExecContext(ctx, deleteServiceAccount, keycloakClientID)
	return err
}

const deleteServiceAccountByID = `-- name: DeleteServiceAccountByID :exec
DELETE FROM service_accounts WHERE id = ?
`

func (q *Queries) DeleteServiceAccountByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteServiceAccountByID, id)
	return err
}

const getServiceAccountByClientID = `-- name: GetServiceAccountByClientID :one
SELECT id, wonder_net_id, keycloak_client_id, name, created_at FROM service_accounts WHERE keycloak_client_id = ?
`

func (q *Queries) GetServiceAccountByClientID(ctx context.Context, keycloakClientID string) (ServiceAccount, error) {
	row := q.db.QueryRowContext(ctx, getServiceAccountByClientID, keycloakClientID)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.WonderNetID,
		&i.KeycloakClientID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listServiceAccountsByWonderNet = `-- name: ListServiceAccountsByWonderNet :many
SELECT id, wonder_net_id, keycloak_client_id, name, created_at FROM service_accounts WHERE wonder_net_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListServiceAccountsByWonderNet(ctx context.Context, wonderNetID string) ([]ServiceAccount, error) {
	rows, err := q.db.QueryContext(ctx, listServiceAccountsByWonderNet, wonderNetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceAccount{}
	for rows.Next() {
		var i ServiceAccount
		if err := rows.Scan(
			&i.ID,
			&i.WonderNetID,
			&i.KeycloakClientID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
