// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlcpostgres

import (
	"context"
	"database/sql"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, wonder_net_id, name, key_hash, key_prefix, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, wonder_net_id, name, key_hash, key_prefix, created_at, last_used_at, expires_at
`

type CreateAPIKeyParams struct {
	ID          string       `json:"id"`
	WonderNetID string       `json:"wonder_net_id"`
	Name        string       `json:"name"`
	KeyHash     string       `json:"key_hash"`
	KeyPrefix   string       `json:"key_prefix"`
	ExpiresAt   sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.ID,
		arg.WonderNetID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WonderNetID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, wonder_net_id, name, key_hash, key_prefix, created_at, last_used_at, expires_at FROM api_keys WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WonderNetID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, wonder_net_id, name, key_hash, key_prefix, created_at, last_used_at, expires_at FROM api_keys WHERE id = $1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WonderNetID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listAPIKeysByWonderNet = `-- name: ListAPIKeysByWonderNet :many
SELECT id, wonder_net_id, name, key_hash, key_prefix, created_at, last_used_at, expires_at FROM api_keys WHERE wonder_net_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByWonderNet(ctx context.Context, wonderNetID string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByWonderNet, wonderNetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.WonderNetID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, id)
	return err
}
