// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wonder_nets.sql

package sqlcsqlite

import (
	"context"
)

const createWonderNet = `-- name: CreateWonderNet :exec
INSERT INTO wonder_nets (id, owner_id, headscale_user, display_name, mesh_type, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type CreateWonderNetParams struct {
	ID            string `json:"id"`
	OwnerID       string `json:"owner_id"`
	HeadscaleUser string `json:"headscale_user"`
	DisplayName   string `json:"display_name"`
	MeshType      string `json:"mesh_type"`
}

func (q *Queries) CreateWonderNet(ctx context.Context, arg CreateWonderNetParams) error {
	_, err := q.db.ExecContext(ctx, createWonderNet,
		arg.ID,
		arg.OwnerID,
		arg.HeadscaleUser,
		arg.DisplayName,
		arg.MeshType,
	)
	return err
}

const deleteWonderNet = `-- name: DeleteWonderNet :exec
DELETE FROM wonder_nets WHERE id = ?
`

func (q *Queries) DeleteWonderNet(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWonderNet, id)
	return err
}

const getWonderNet = `-- name: GetWonderNet :one
SELECT id, owner_id, headscale_user, display_name, mesh_type, created_at, updated_at FROM wonder_nets WHERE id = ?
`

func (q *Queries) GetWonderNet(ctx context.Context, id string) (WonderNet, error) {
	row := q.db.QueryRowContext(ctx, getWonderNet, id)
	var i WonderNet
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.HeadscaleUser,
		&i.DisplayName,
		&i.MeshType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWonderNetByHeadscaleUser = `-- name: GetWonderNetByHeadscaleUser :one
SELECT id, owner_id, headscale_user, display_name, mesh_type, created_at, updated_at FROM wonder_nets WHERE headscale_user = ?
`

func (q *Queries) GetWonderNetByHeadscaleUser(ctx context.Context, headscaleUser string) (WonderNet, error) {
	row := q.db.QueryRowContext(ctx, getWonderNetByHeadscaleUser, headscaleUser)
	var i WonderNet
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.HeadscaleUser,
		&i.DisplayName,
		&i.MeshType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWonderNets = `-- name: ListWonderNets :many
SELECT id, owner_id, headscale_user, display_name, mesh_type, created_at, updated_at FROM wonder_nets ORDER BY created_at DESC
`

func (q *Queries) ListWonderNets(ctx context.Context) ([]WonderNet, error) {
	rows, err := q.db.QueryContext(ctx, listWonderNets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WonderNet{}
	for rows.Next() {
		var i WonderNet
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.HeadscaleUser,
			&i.DisplayName,
			&i.MeshType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWonderNetsByOwner = `-- name: ListWonderNetsByOwner :many
SELECT id, owner_id, headscale_user, display_name, mesh_type, created_at, updated_at FROM wonder_nets WHERE owner_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListWonderNetsByOwner(ctx context.Context, ownerID string) ([]WonderNet, error) {
	rows, err := q.db.QueryContext(ctx, listWonderNetsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WonderNet{}
	for rows.Next() {
		var i WonderNet
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.HeadscaleUser,
			&i.DisplayName,
			&i.MeshType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWonderNet = `-- name: UpdateWonderNet :exec
UPDATE wonder_nets
SET display_name = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateWonderNetParams struct {
	DisplayName string `json:"display_name"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateWonderNet(ctx context.Context, arg UpdateWonderNetParams) error {
	_, err := q.db.ExecContext(ctx, updateWonderNet, arg.DisplayName, arg.ID)
	return err
}
