// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, issuer, subject, created_at, expires_at, last_used_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID         string       `json:"id"`
	UserID     string       `json:"user_id"`
	Issuer     string       `json:"issuer"`
	Subject    string       `json:"subject"`
	CreatedAt  time.Time    `json:"created_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	LastUsedAt time.Time    `json:"last_used_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Issuer,
		arg.Subject,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at IS NOT NULL AND expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, issuer, subject, created_at, expires_at, last_used_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getSessionByUserID = `-- name: GetSessionByUserID :many
SELECT id, user_id, issuer, subject, created_at, expires_at, last_used_at FROM sessions WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) GetSessionByUserID(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessionByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Issuer,
			&i.Subject,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionLastUsed = `-- name: UpdateSessionLastUsed :exec
UPDATE sessions SET last_used_at = ? WHERE id = ?
`

type UpdateSessionLastUsedParams struct {
	LastUsedAt time.Time `json:"last_used_at"`
	ID         string    `json:"id"`
}

func (q *Queries) UpdateSessionLastUsed(ctx context.Context, arg UpdateSessionLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
